@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

class Company {
-Designation
}

class Container {
-Identification
-Payload
-Tare
-Gross
-Width
-Height
-Length
-Refrigerated
-Temperature
}

class Ship {
-MMSI
-Name
-IMO
-Number of Energy Generators
-Generators' Power Output
-Call sign
-Vessel type
-Length
-Width
-Capacity
-Draft
-FleetManager
-ShipCaptain
-ShipChiefElectricalEngineer
}

class ShipPosition {
-Base Date Time
-Latitude
-Longitude
-Speed over ground SOG
-Course over ground COG
-Heading
-Position
-Transceiver Class
}

class Truck {
-TruckDriver
}

class Client

class Port {
-Identification
-Name
-Continent
-Country
-Latitude
-longitude
-PortMagager
-PortStaff
}

class Warehouse {
-Identification
-Name
-Continent
-Country
-Latitude
-longitude
-WarehouseManager
-WarehouseStaff
}

class Employee {
-Name
-Email
-Password
}

class OrganizationRole {
-Description
}

class TrafficManager

class CargoManifest

class UnloadingCargoManifest

class LoadingCargoManifest

Company "1" -- "*" Shipping : Performs >
Company "1" -- "1..*" Ship : Owns >
Company "1" -- "1..*" Truck : Owns >
Company "1" --- "*" Port : Owns >
Company "1" --- "*" Warehouse : Owns >
Company "1" -- "*" Employee : Employs >
Company "1" -- "*" CargoManifest : Knows >
Company "1" --- "*" OrganizationRole : Comprehends >
Employee "*" - "1" OrganizationRole : Has/Plays >
Shipping "1" -- "1" Client : Requested by >
Ship "1" -- "*" Container : Transports >
Ship "1" -- "1..*" ShipPosition : has >
TrafficManager "1" - "*" ShipPosition : Controls >
TrafficManager "1" -- "*" Truck : Controls position of >
Truck "1" -- "1" Container : Transports >
UnloadingCargoManifest --|> CargoManifest
LoadingCargoManifest --|> CargoManifest
CargoManifest "1" -- "*" Container : Keeps track of >

@enduml