@startuml
autonumber

'hide footbox
actor "Traffic Manager" as TM

participant ":SearchShipUI" as UI
participant ":SearchShipController" as CTRL
participant ":SearchShip" as SS
participant ":App" as APP
participant ":Company" as COMP

activate TM
TM -> UI : asks for details of a ship
activate UI
activate CTRL

UI -> TM : requests data (code)
TM -> UI : types requested data

autonumber 3.1
UI -> CTRL : chosenShip = findShip(code)

CTRL -> SS : chosenShip = findShip(code)
activate SS

SS -> APP : app = getInstance()
activate APP
SS -> APP : company = getCompany
deactivate APP
SS -> COMP : ships = getShipBST()
activate COMP
deactivate COMP

SS -> SS : codeType = DetermineCodeType(code)

alt codeType = MMSI
  SS -> SS : chosenShip = findShipByMMSI(MMSI)
else codeType = IMO
  SS -> SS : chosenShip = findShipByIMO(IMO)
else codeType = CallSign
  SS -> SS : chosenShip = findShipByCallSign(CallSign)
end

deactivate SS
deactivate CTRL

autonumber 4
UI --> TM : shows details of the corresponding ship
deactivate UI

deactivate TM

@enduml