@startuml
'https://plantuml.com/use-case-diagram

left to right direction

:User: as USER
(Get the  top-N ships with the most kilometres travelled and their average speed) as (Use)

USER ---> (Use)

@enduml