@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Port Staff" as PS

activate PS
PS -> ":System" : asks for number of free/occupied slots

activate ":System"
":System" --> "PS" : requests data (ship imo)
deactivate ":System"

PS -> ":System" : types requested data

activate ":System"
":System" --> PS : shows number of free/occupied slots
deactivate ":System"

deactivate PS

@enduml