@startuml
'https://plantuml.com/class-diagram

class ContainersRoutesUI {
- controller
}

class ContainersRoutesController {
- ContainersRouteStoreDb
+ getContainersRoutes(userID, containerID)
}

class ContainersRouteStoreDb {
+ getContainersRoutes(userID, containerID)
}

class ContainersRoute {
- startingPoint
- endingPoint
- startingDateTime
- endingDateTime
- transport

+ ContainersRoute(startingPoint, endingPoint,\n startingDateTime, endingDateTime, transport)
+ toString()
}

ContainersRoutesController <.. ContainersRoutesUI
ContainersRouteStoreDb <.. ContainersRoutesController
ContainersRoute <-- ContainersRouteStoreDb
ContainersRoute <.. ContainersRoutesUI

@enduml