@startuml
'https://plantuml.com/class-diagram

class CrewUI {
- controller
}

class CrewController {
+ getContainersOfShip(shipID)
}

class DatabaseFunctions {
+ getContainersOfShip(databaseConnection, shipID)
- loadFunction(filename)
- getResultSetFromSysRefCursor(databaseConnection, function, columnsForTable) throws SQLException
}


CrewController <.. CrewUI
DatabaseFunctions <.. CrewController

@enduml