@startuml

entity Trip {
* id_trip
--
* ship_imo
* id_start_port
* id_destination_port
}

entity Container {
* id_container
--
* iso_code

* tare
* max_weight_incl_container
* max_weight
* max_volume

* id_owner
* id_equipment
* serial_number
* check_digit
}

entity ISO {
* iso_code
--
* length_code
* width_height_code
* container_type_code
* reduced_strength_code
}

entity Length {
* length_code
--
* value
}

entity Width_Height {
* width_height_code
--
* value
}

entity Container_Type {
* container_type_code
--
* value
}

entity Reduced_Strength {
* reduced_strength_code
--
* value
}

entity Cargo_Manifest {
* id_cargo_manifest
--
* id_destination_port
* date_time_start
* date_time_end
}

entity Trip_Manifests {
* id_cargo_manifest
* id_trip
--
}

entity Container_Shipping {
* id_cargo_manifest
* id_container
--
* position_code
* cargo_weight
* refrigeration_temperature
}

entity Container_Client {
* id_cargo_manifest
* id_container
* id_client
--
}

entity Truck {
* id_truck
--
* id_employee
}

entity Ship {
* imo_code
--
* mmsi_code
* name_ship
* number_generators
* power_out_generator
* call_sign
* vessel_type
* Length_ship
* width_ship
* capacity_ship
* draft
}

entity Port {
* id_port
--
* name_port
* continent_port
* country_port
* latitude_port
* longitude_port
}

entity Warehouse {
* id_warehouse
--
* name
* continent
* country
* latitude
* longitude
}

entity Employee{
* id_employee
--
* role_id
* name_employee
* user_password
 address_employee
 phone_employee
}

entity Position_Ship {
* imo_code
* base_date_time
--
* latitude
* longitude
* sog
* cog
* heading
* position
* transceiver_class
}

entity Role {
* role_id
--
* designation
}

entity Client {
* id_client
--
* name
* address
* phone_number
}

entity Container_Owner {
* id_owner
--
* name_owner
}

entity Container_Equipment_Identifier {
* id_equipment
--
* description
}

ISO }o--|| Length
ISO }o--|| Width_Height
ISO }o--|| Container_Type
ISO }o--|| Reduced_Strength

Container }o--|| Container_Owner
Container }o--|| Container_Equipment_Identifier
Container }o--|| ISO
Cargo_Manifest ||--|{ Container_Shipping
Container_Shipping }|--|| Container
Container_Shipping ||--|{ Container_Client
Container_Client }|--|| Client
Trip ||--|{ Trip_Manifests
Trip_Manifests }|--|| Cargo_Manifest
Ship ||--o{ Position_Ship

Truck ||--o{ Employee
Ship ||--o{ Trip
Ship ||--o{ Employee
Warehouse ||--o{ Employee
Port ||--o{ Employee
Employee }o--|| Role

@enduml