@startuml

entity Contianer_Operation {
* id_cargo_manifest         integer
* id_container              char(11)
* base_date_time            timestamp
--
* id_employee               integer
* type_operation            char(1)
}

entity Type_Operation {
* code                      char(1)
--
* description               char(6)
}


entity Trip {
* id_trip                   integer
--
* ship_imo                  char(10)
* id_truck                  integer
* id_start_port             char(5)
* id_destination_port       char(5)
* id_start_warehouse        integer
* id_destination_warehouse  integer
* date_time_start           timestamp
* date_time_end             timestamp
}

entity Container {
* id_container              char(11)
--
* iso_code                  char(4)

* tare                      integer
* max_weight_incl_container integer
* max_weight                integer
* max_volume                number(3,1)

* id_owner                  char(3)
* id_equipment              char(1)
* serial_number             integer
* check_digit               integer
}

entity ISO {
* iso_code                  char(4)
--
* length_code               char(1)
* width_height_code         char(1)
* container_type_code       char(2)
}

entity Length {
* length_code               char(1)
--
* value                     integer
}

entity Width_Height {
* width_height_code         char(1)
--
* value                     integer
}

entity Container_Type {
* container_type_code       char(2)
--
* value                     varChar(200)
}

entity Cargo_Manifest {
* id_cargo_manifest         integer
* id_container              char(11)
--
* id_trip                   integer
* position_code             number(6,0)
* cargo_weight              integer
* refrigeration_temperature number(3,1)
* id_client                 integer
}

entity Unloading_Cargo_Manifest {
* id_cargo_manifest         integer
* id_container              char(11)
--
* id_warehouse              integer
}

entity Loading_Cargo_Manifest {
* id_cargo_manifest         integer
* id_container              char(11)
--
* id_warehouse              integer
}

entity Truck {
* id_truck                  integer
--
* id_employee               integer
}

entity Ship {
* imo_code                  char(10)
--
* mmsi_code                 integer
* name_ship                 varChar(30)
* number_generators         integer
* power_out_generator       integer
* call_sign                 varChar(9)
* vessel_type               integer
* Length_ship               integer
* width_ship                integer
* capacity_ship             integer
* draft                     number(3,1)
* id_employee_captain       integer
}

entity Port {
* id_port                   integer
--
* name                      varChar(20)
* country_code              char(2)
* latitude                  number(12,9)
* longitude                 number(12,9)
}

entity Warehouse {
* id_warehouse              integer
* name    	   			    varChar(30)
* country_code              char(2)
* latitude		    	    number(12,9)
* longitude 	    	    number(12,9)
}

entity Employee{
* id_employee               integer
--
* role_id                   integer
* name_employee             varChar(30)
* user_password             varChar(15)
 address_employee           varChar(30)
 phone_employee             integer
}

entity Position_Ship {
* imo_code                  char(10)
* base_date_time            timestamp
--
* latitude                  number(12,9)
* longitude                 number(12,9)
* sog                       number(4,1)
* cog                       number(4,1)
* heading                   integer
* transceiver_class         char(1)
* cargo                     integer
}

entity Role {
* role_id                   integer
--
* designation               varChar(30)
}

entity Client {
* id_client                 integer
--
* name                      varChar(30)
* address                   varChar(40)
* phone_number              integer
}

entity Container_Owner {
* id_owner                  char(3)
--
* name_owner                varChar(40)
}

entity Container_Equipment_Identifier {
* id_equipment              char(1)
--
* description               varChar(100)
}

entity Country {
* alpha2_code               char(2)
--
* alpha3_code               char(3)
* capital                   varChar(30)
* country                   varChar(20)
* continent                 varChar(10)
* population                integer
* latitude                  number(12,9)
* longitude                 number(12,9)
}

entity Border {
* country1                  char(2)
* country2                  char(2)
}

entity Sea_Distance {
* id_port1                  char(5)
* id_port2                  char(5)
--
* distance                  integer
}


ISO }o--|| Length
ISO }o--|| Width_Height
ISO }o--|| Container_Type

Container }o--|| Container_Owner
Container }o--|| Container_Equipment_Identifier
Container }o--|| ISO
Trip ||--|| Cargo_Manifest
Cargo_Manifest }o--|| Container
Cargo_Manifest }|--|| Client
Position_Ship }o--|| Ship

Employee }o--|| Truck
Trip }o--|| Truck
Ship ||--o{ Trip
Ship ||--o{ Employee
Warehouse ||--o{ Employee
Port ||--o{ Employee
Employee }o--|| Role

Unloading_Cargo_Manifest ||--|| Cargo_Manifest
Loading_Cargo_Manifest ||--|| Cargo_Manifest

Country ||--o{ Port
Country ||--o{ Warehouse
Country }|--o| Border
Country }|--o| Border
Sea_Distance ||--|{ Port
Sea_Distance ||--|{ Port

Cargo_Manifest ||--|{ Contianer_Operation
Contianer_Operation }o--|| Type_Operation

@enduml