@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Ship Captain" as SP

activate SP
SP -> ":System" : asks for container's route

activate ":System"
":System" --> "SP" : requests data (userID, containerID)
deactivate ":System"

SP -> ":System" : types requested data

activate ":System"
":System" --> SP : shows container operations of the chosen manifest
deactivate ":System"

deactivate SP

@enduml