@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Client" as C

activate C
C -> ":System" : asks for container's route

activate ":System"
":System" --> "C" : requests data (userID, containerID)
deactivate ":System"

C -> ":System" : types requested data

activate ":System"
":System" --> C : shows container's route and other details
deactivate ":System"

deactivate C

@enduml