@startuml
'https://plantuml.com/class-diagram

class ContainersRoutesUI {
- controller
}

class ContainersRoutesController {
+ getContainersRoutes(userID, containerID)
}

class DatabaseFunctions {
+ getContainersRoutes(databaseConnection, userID, containerID)
- loadFunction(filename)
- getResultSetFromSysRefCursor(databaseConnection, function, columnsForTable) throws SQLException
}



ContainersRoutesController <.. ContainersRoutesUI
DatabaseFunctions <.. ContainersRoutesController

@enduml