@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Traffic Manager" as TM

activate TM
TM -> ":System" : Asks the amount of auxiliary power equipment necessary for a trip

activate ":System"
":System" --> "TM" : requests data (energy per type of container, energy as function of container positions)
deactivate ":System"

TM -> ":System" : types requested data

activate ":System"
":System" --> "TM" : Shows amount of 75KW generators required for the trip
deactivate ":System"

deactivate TM

@enduml