@startuml
'https://plantuml.com/class-diagram

class ImportPortsUI {
- controller
}

class ImportPortsController {
+ ImportPorts()
}

class Port {
- identification
- name
- continent
- country
- latitude
- longitude
+ Port(identification, name, continent, country, latitude, longitude)
}

class Port2DTree {
+ createdBalancedPort2DTree()
}

ImportPortsController <.. ImportPortsUI
Port2DTree <.. ImportPortsController
Port <-- ImportPortsController

@enduml