@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Ship Captain" as SC

activate SC
SC -> ":System" : Asks where to position containers on the vessel

activate ":System"
":System" --> SC : asks for containers, x, y, z max and original center of mass
deactivate ":System"

SC -> ":System" : types requested data

activate ":System"
":System" --> SC : returns layout of containers and new center of mass
deactivate ":System"

deactivate SC

@enduml