@startuml
'https://plantuml.com/class-diagram

entity Country {
* alpha2_code
--
* alpha3_code
* capital
* country
* continent
* population
* latitude
* longitude
}

entity Port {
* id_port
--
* name
* country_code
* latitude
* longitude
* capacity
}

entity Border {
* country1
* country2
}


Country ||--o{ Port
Country }|--o| Border
Country }|--o| Border


@enduml