@startuml
'https://plantuml.com/class-diagram

class ColourMapUI {
- controller
}

class ColourMapController {
+ calculateNumberOfColours(Graph grafo)
+ colourMap(Graph<V, E> grafo)
+ atributeColour(List<V> l, Map<V, Integer> map, int numberOfColours)
}


class Company {
+ getFreightNetwork()
}

class FreightNetwork{
+ FreightNetwork(List<Object> vertices, Long[][] m)
}

ColourMapController <.. ColourMapUI
Company <.. ColourMapController
FreightNetwork <.. Company



@enduml