@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Traffic Manager" as TM

participant ":ColourMapUI" as UI
participant ":ColourMapController" as CTRL
participant ":Company" as COMP
participant ":FreightNetwork" as NET

activate TM
TM -> UI : asks to colour the map

activate UI
UI -> CTRL : colourMap()

activate CTRL
CTRL->COMP : getCompany()

activate COMP
COMP->NET : getFreightNetwork()

activate NET
deactivate NET
deactivate COMP

CTRL -> CTRL : calculateNumberOfColours()

CTRL -> CTRL : atributeColour()

CTRL -> CTRL : colourMap()

UI -> TM : Map associated with colours is printed

deactivate CTRL
deactivate UI




@enduml