@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Traffic Manager" as TM

activate TM
TM -> ":System" : asks to colour the map

activate ":System"
":System" --> ":System" : colours the map using as few colours as possible
deactivate ":System"

deactivate TM

@enduml