@startuml
'https://plantuml.com/class-diagram

class TripEnergyUI {
- controller
}

class TripEnergyController {
+ getTripEnergy(trip ID)
+ calculateTripEnergy()
}

class DatabaseFunctions {
+ getTripEnergyDetails(trip ID)
}

TripEnergyController <.. TripEnergyUI
DatabaseFunctions <.. TripEnergyController

@enduml