@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Ship Chief Electrical Engineer" as SCEE

activate SCEE
SCEE -> ":System" : Asks for total energy required for a trip

activate ":System"
":System" --> "SCEE" : requests data (trip ID)
deactivate ":System"

SCEE -> ":System" : types requested data

activate ":System"
":System" --> "SCEE" : Shows total energy for 7ºC containers and for -5ºC containers
deactivate ":System"

deactivate SCEE

@enduml