@startuml
'https://plantuml.com/class-diagram

class TripEnergyUI {
- controller
}

class TripEnergyController {
- tripStoreDb
+ getTripEnergy(trip ID)
}

class TripStoreDb {
+ getTripEnergy(trip ID)
}

TripEnergyController <.. TripEnergyUI
TripStoreDb <.. TripEnergyController

@enduml