@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Traffic Manager" as TM

activate TM
TM -> ":System" : asks for details of a ship's movements

activate ":System"

":System" --> TM : requests data (code)
deactivate ":System"

TM -> ":System" : types requested data

activate ":System"
":System" --> TM : shows details of the corresponding ship's movements
deactivate ":System"

deactivate TM

@enduml