@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Ship Captain" as SP

activate SP
SP -> ":System" : asks for map of port resources

activate ":System"
":System" --> "SP" : requests data (month)
deactivate ":System"

SP -> ":System" : types requested data

activate ":System"
":System" --> SP : shows map of port resources
deactivate ":System"

deactivate SP

@enduml