@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0

left to right direction

class CargoManifest {
-Destination
-Date_time_start
-Date_time_end
}

class Container {
-Identification
-Payload
-Tare
-Gross
-Width
-Height
-Length
-Refrigerated
-Temperature
}

CargoManifest "*" -- "1..*" Container : Keeps track of >
@enduml