@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Traffic Manager" as TM

participant ":buildFreightNetworkUI" as UI
participant ":buildFreightNetworkController" as CTRL
participant ":PortStore" as P
participant ":SeaDistanceStore" as SD
participant ":BorderStore" as B
participant ":CountryStore" as C
participant ":FreightNetwork" as NET

activate TM
TM -> UI : asks to build a freight network

activate UI
UI -> CTRL : buildFreightNetwork()

activate CTRL

CTRL -> P : ports = getPorts()
activate P
deactivate P

CTRL -> SD : seaDists = getSeaDistances()
activate SD
deactivate SD

CTRL -> B : borders = getBorders()
activate B
deactivate B

CTRL -> C : countries = getCountries()
activate C
deactivate C

CTRL -> CTRL : buildFreightNetwork()

create NET
CTRL --> NET : BuildFreightNetwork(false, vs, m)

deactivate NET
deactivate CTRL
deactivate UI
deactivate TM
@enduml