@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Traffic Manager" as TM

participant ":ClosestPlacesUI" as UI
participant ":ClosestPlacesController" as CTRL
participant "FreightNetwork" as NET
participant "Company" as C
participant "Algorithms" as ALG

activate TM
TM -> UI : asks to know which places are closest to all other places

activate UI
UI --> TM : asks for the number of countries per continent
deactivate UI

TM -> UI : types requested data

activate UI
UI -> CTRL : closestPlaces(n)

activate CTRL

alt Freight Network does not exist
CTRL -> NET : BuildFreightNetwork()
activate NET
deactivate NET
end

CTRL -> C : freightNetwork = getFreightNetwork().clone()
activate C
deactivate C

CTRL -> ALG : shortPathsMatrix = minDistGraph(freightNetwork,Integer::compare,Integer::sum)
activate ALG
deactivate ALG

CTRL -> CTRL : result = closestPlaces(shortPathsMatrix, n)







UI --> TM : returns the countries divided by continents
deactivate CTRL
deactivate UI
deactivate TM
@enduml