@startuml
'https://plantuml.com/class-diagram

class TripGeneratorsUI {
- controller
}

class TripGeneratorsController {
+ getTripGenerators()
}

TripGeneratorsController <.. TripGeneratorsUI

@enduml